### ISSUE TITLE
Predictions by data point

### ISSUE THREAD

**Issue by fusaroli** [victor-m-p/BayesWorkflow#1]
The posterior predictive checks are great, but it'd be really useful to see how the predictions compare to the actual data points one by one. Imagine a plot where the real data are dots, and the predictions a dot with CIs

**Comment by victor-m-p** [comment]
Hi Riccardo, 
Thanks for the ffeedback! 
I know exactly what you mean (visually at least). 
However, would you want to have this plot in the last "prediction" section,
or do you think that it should be part of the core "work-flow" - 
and be shown for each "candidate model"?

**Comment by fusaroli** [comment]
both :-P
I was actually thinking it as part of the core workflow. pred post checks are great, but you might in principle have a perfect ppcheck and still crappy predictions (e.g. inverted). see also discussion here: https://twitter.com/fusaroli/status/1398193938800971776?s=20

**Comment by victor-m-p** [comment]
Cool,
I agree that this would be good, and should be one of the main priorities going forward.
I will have a look in the near future and report back :)

**Comment by victor-m-p** [comment]
I have now implemented this in the sections: "Random Intercepts", "Multilevel Covariation" & "Predictions".
Does not really make sense for the "Complete Pooling" model I think, as we are not estimating any random effects
(that would allow us to make predictions by groups/ID). Let me know if the plots I've incorporated are what you
were thinking. If so, I'll close this thread.

**Comment by fusaroli** [comment]
looks good. might comment a bit on whether it's good fit or not and when it wouldn't be.
