### ISSUE TITLE
text improvements

### ISSUE THREAD

**Issue by fusaroli** [victor-m-p/BayesWorkflow#3]
1. "whether our priors are on a reasonable scale as compared to the data". Define what reasonable is. E.g. show two bad prior predictive checks (see my slides from the intensive course)
2.  "notice that the posterior has not adapted well here (too constrained by the strong prior to properly learn from the data)" walk the reader through what is not well adapted, describe the pattern

[to be continued]

**Comment by victor-m-p** [comment]
Yes, a lot of the text is not worked through thoroughly enough at this point. 
Will check your slides (and other sources) & tighten it up when I get the time.

**Comment by victor-m-p** [comment]
I've now tried to polish the writing a bit (mainly in the sections you've highlighted). 
Let me know whether we can close this thread, or whether you still have objections :)

**Comment by fusaroli** [comment]
looks good! I'll add more when I have time to go through the details again
